### ISSUE TITLE
Refactor secnetperf tests into a callable workflow

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/netperf#118]
Both eBPF and QUIC use the secnet tests for performance testing. Rather than cutting and pasting code, it would be better to refactor this into a shared callable workflow.

**Comment by ProjectsByJackHe** [comment]
Done. Please see: https://github.com/microsoft/netperf/pull/134, and https://github.com/microsoft/netperf/actions/runs/8502514788
