### ISSUE TITLE
Consider Moving PATs to Azure Key Vault

### ISSUE THREAD

**Issue by nibanks** [microsoft/netperf#162]
See example: https://github.com/microsoft/ebpf-for-windows/blob/c4b7fe423402fa66ff243ec02a451c354ca4be83/.github/workflows/upload-perf-results.yml#L80C1-L87C1

This would eliminate the need to store them with GitHub.

**Comment by ProjectsByJackHe** [comment]
See https://github.com/microsoft/netperf/issues/209
