### ISSUE TITLE
Remove dependencies on PATs

### ISSUE THREAD

**Issue by mtfriesen** [microsoft/netperf#209]
PATs need manual rotation, and although #162 would reduce the burden on individual projects, PATs ultimately are error-prone, a maintenance chore, and AFAIK no longer considered a security best practice.

**Comment by ProjectsByJackHe** [comment]
Agree 100%. We are moving ahead with Azure testing using 1ES pools, and recently merged my changes that includes the code to enable our testing scenario (2-machine perf) on 1ES infra. 

This eliminates the need for PATs. I have since removed PATs from the secrets section of this repo.
