### ISSUE TITLE
404 on subpaths

### ISSUE THREAD

**Issue by maolson-msft** [microsoft/netperf#25]
Scenario:

1) I navigate to https://microsoft.github.io/netperf/dist/.
2) I click e.g. the "latency" tab, which changes my URL bar to https://microsoft.github.io/netperf/dist/latency.
3) I see some interesting data, and copy the current URL to send to my compatriot.
4) Compatriot gets a 404.

This appears to be a well-known issue with SPAs: https://stackoverflow.com/questions/46056414/getting-404-for-links-with-create-react-app-deployed-to-github-pages

**Comment by ProjectsByJackHe** [comment]
Fixed by adding a 404.html with same contents as the root, so redirection handles client side.
