### ISSUE TITLE
Enable dependabot to keep workflow tasks current

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/netperf#319]
Workflow failure was observed as an older version of the artifact upload/download task was deprecated. If this repo used dependabot then this would not have occurred.

https://github.com/microsoft/netperf/actions/runs/10807602492

**Comment by ProjectsByJackHe** [comment]
Dependabot is/was enabled. 

Hmm, the PR to bump the version of upload/download artifact got missed for some reason. 

I'll be on the lookout for future PRs and accept them.

**Comment by ProjectsByJackHe** [comment]
netperf team will be on the lookout for future dependabot PRs and accept them.
