### ISSUE TITLE
Enable Experimental Boost SKU size to run in our 1ES Machine Pools. 

### ISSUE THREAD

**Issue by nibanks** [microsoft/netperf#72]
We use [Standard F4s v2](https://learn.microsoft.com/en-us/azure/virtual-machines/fsv2-series) VMs in Azure currently, which document their max throughput at 10000 Mbps. Based on the data we're seeing for TCP throughput, it looks like we are hitting that limit:

![image](https://github.com/microsoft/netperf/assets/20663557/4e03525d-c636-4f78-81df-75a23fbb5685)

We will probably need to increase the VM size.

The `Standard_F8s_v2` VMs (2x cost) increases the limit to 12500 Mbps. The next bandwidth limit isn't until the `Standard_F32s_v2` size, which has 16000 Mbps, but is 8x the cost!

![image](https://github.com/microsoft/netperf/assets/20663557/fe54b166-39d3-4cdb-b0bb-2d6cc4a893ac)

**Comment by ProjectsByJackHe** [comment]
Given the high cost, we could perform a few test runs with the beefiest VM package, to see what the "ceiling" is, and then choose the tightest upper bound later. Thoughts?

**Comment by nibanks** [comment]
I agree the costs are an issue. But I also feel that if we don't increase the size, then there isn't much reason to run the tests because we're just measuring the bottleneck limit. I will try to follow up internally to see what our options are.

**Comment by ProjectsByJackHe** [comment]
Updated title of issue, now that the perf stuff has been resolved. The goal is to replace our entire fleet of F4 VMs.
