### ISSUE TITLE
Netperf version 1.5 TODO: Automatic Provisioning of Azure VMs

### ISSUE THREAD

**Issue by nibanks** [microsoft/netperf#74]
We need to figure out a solution to automatically deploy/provision the Azure VMs on demand. We might be able to do this easily enough by having a 'setup job/step' that uses the Azure CLI to create the VMs and then run the provisioning script on them. This script would start add the VM to the desired pool (for a single job). Then all subsequent jobs could leverage the pool.

**Comment by ProjectsByJackHe** [comment]
Windows work reliably well. 

Linux is WIP.
