### ISSUE TITLE
Collect Detailed Latency Data

### ISSUE THREAD

**Issue by nibanks** [microsoft/netperf#78]
We need to collect and store the full latency curve (~50 data points) for each latency run.

**Comment by ProjectsByJackHe** [comment]
That would be 50 columns per row if we stored it all in the database. We could commit a txt file to the sqlite branch, and store the URL in the database instead. We could probably store the 8 that we have for querying. Thoughts?

**Comment by nibanks** [comment]
I'm fine if the data isn't in the database, or if it's encoded in some not easily consumable format in the db (base64 string for instance). My primary goal is that the data is viewable via the dashboard.
