### ISSUE TITLE
Migrate off of using filenames to pass environment data [NEED TO INCLUDE HYPHEN FOR os_name]

### ISSUE THREAD

**Issue by ProjectsByJackHe** [microsoft/netperf#94]
As of today, as part of the SQL automation, we use a fixed format for filenames we save in our pipeline. 

That fixed format allows us to build an automation that parses for keywords and query the database.

As a consequence of this, because we split the names with a hyphen "-" (i.e.: test-results-ubuntu-20.05-x64) we use the hyphen as a delimiter. 

Notice how the name "ubuntu-20.05" has a hyphen in it even though its 1 atomic item we want parsed. This makes the parsing logic extra complicated, and requires all future OS_names in the YAML to include a hyphen. 

In the short term, this is OK, but when we refactor, this is 1 area to be improved upon.

**Comment by nibanks** [comment]
In the short term, should we simply use `.` as the delimiter?

**Comment by ProjectsByJackHe** [comment]
> In the short term, should we simply use `.` as the delimiter?

OS names like "ubuntu-20.05" also has a `.` in it sometimes. In the short term, I think the logic (although ugly) isn't that complicated for an immediate refactor. I wanted to have this issue to track this, once we stand CTS and everything else up.

**Comment by nibanks** [comment]
You're right. Maybe `_` then?
